#!/bin/bash
#
# enkive     Startup script for enkive
#
# chkconfig: - 64 36
# description: Enkive e-mail Archiver
#
# processname: enkive
#


# SYSTEM ADMINISTRATOR LIKELY WANTS TO MODIFY THE FOLLOWING VARIABLES

# user id under which Enkive is run; a good practice is to create a
# user specifically to run Enkive (e.g., "enkive")
ENKIVE_USER=${ENKIVE_USER:-"enkive"}

# path to top-level Enkive directory; this directory would contain
# "lib" and "config"
ENKIVE_HOME=${ENKIVE_HOME:-${PWD}}

# path to the jsvc executable file
JSVC=/usr/bin/jsvc

# path to top level of the Java JDK (must be a JDK and not a JRE);
# should contain "bin", "lib", and "lib/tools.jar"
JAVA_HOME=${JAVA_HOME:-"/opt/java"}

# path to directory that Indri was installed in -- typically /usr/local
# or /opt/indri. Expect to find underneath this directory both
# lib/libindri_jni.so and share/indri/indri.jar . 
INDRI_INSTALL_PATH=${INDRI_INSTALL_PATH:-"/usr/local"}

# Uncomment this to increase the maximum heap size.  Default is 1/4 RAM
#MAXHEAP="2500M"

# Make sure to set your locale, and use a UTF-8 locale
export LANG=en_US.UTF-8

# TESTING OF THE ABOVE

errors=0

if [ ! -f ${JAVA_HOME}/bin/javac -o ! -f ${JAVA_HOME}/lib/tools.jar ] ;then
	echo "JAVA_HOME (${JAVA_HOME}) is likely set incorrectly."
	errors=1
fi

if [ ! -d ${ENKIVE_HOME}/config -o ! -d ${ENKIVE_HOME}/lib ] ;then
	echo "ENKIVE_HOME (${ENKIVE_HOME}) is likely set incorrectly."
	errors=1
fi

INDRI_LIB_PATH=${INDRI_INSTALL_PATH}/lib
INDRI_SO_PATH=${INDRI_LIB_PATH}/libindri_jni.so
if [ ! -f ${INDRI_SO_PATH} ] ;then
	echo "INDRI_INSTALL_PATH (${INDRI_INSTALL_PATH}) is likely set incorrectly; could not find ${INDRI_SO_PATH} . "
	errors=1
fi

INDRI_JAR_PATH=${INDRI_INSTALL_PATH}/share/indri/indri.jar
if [ ! -f ${INDRI_JAR_PATH} ] ;then
	echo "INDRI_INSTALL_PATH (${INDRI_INSTALL_PATH}) is likely set incorrectly; could not find ${INDRI_JAR_PATH} . "
	errors=1
fi

if [ ! -f ${JSVC} ] ;then
	echo "JSVC (${JSVC}) is likely set incorrectly."
	errors=1
fi

if grep --silent "^${ENKIVE_USER}:" /etc/passwd ;then
	:
else
	echo "ENKIVE_USER (${ENKIVE_USER}) is likely set incorrectly."
	errors=1
fi

if [ ${errors} -eq 1 ] ;then
	echo "Exiting due to error(s). See comments in $0 for guidance."
	exit 1
fi


# system administrator may not (or may) want to edit the following

ENKIVE_LOG_PATH=${ENKIVE_HOME}/data/logs
ENKIVE_PID_FILE=${ENKIVE_HOME}/data/enkive.pid
ENKIVE_CLASSPATH=${ENKIVE_HOME}/enkive.jar:${INDRI_JAR_PATH}:${ENKIVE_HOME}/lib/*:${ENKIVE_HOME}/lib/spring/*:${ENKIVE_HOME}/lib/james-imap/*:${ENKIVE_HOME}/lib/commons/*:${ENKIVE_HOME}/config:${JAVA_HOME}/lib/tools.jar
JSVC_ARGS="-cwd ${ENKIVE_HOME} -java-home ${JAVA_HOME} -pidfile ${ENKIVE_PID_FILE} -outfile ${ENKIVE_LOG_PATH}/enkive.log -errfile ${ENKIVE_LOG_PATH}/enkive.err -cp ${ENKIVE_CLASSPATH} -Dlog4j.configuration=file://${ENKIVE_HOME}/config/log4j.properties -Djava.library.path=${INDRI_LIB_PATH} com.linuxbox.enkive.EnkiveDaemon"

if [ -n "${MAXHEAP}" ]; then
	JSVC_ARGS="-Xmx${MAXHEAP} $JSVC_ARGS"
fi

# the following should likely not be edited

RETVAL=0

start() {
        echo -n "Starting Enkive:  "
        $JSVC -user ${ENKIVE_USER} $JSVC_ARGS
        RETVAL=$?
        sleep 2
        echo
}

stop() {
        echo -n "Stopping Enkive: "
        $JSVC -user ${ENKIVE_USER} -stop $JSVC_ARGS
        RETVAL=$?
        echo
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        RETVAL=1
esac

exit $RETVAL
