/*******************************************************************************
 * Copyright 2013 The Linux Box Corporation.
 * 
 * This file is part of Enkive CE (Community Edition).
 * Enkive CE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 * 
 * Enkive CE is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public
 * License along with Enkive CE. If not, see
 * <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package com.linuxbox.enkive.statistics.consolidation;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface Consolidator {
	/**
	 * Consolidates data for all the stats gatherers defined in the client
	 */
	public List<Map<String, Object>> consolidateData();

	/**
	 * Stores data generated by consolidateData()
	 */
	public void storeConsolidatedData();

	/**
	 * This method takes a gathername and querys the mongo database on a
	 * grainType and date range as specified by the type of grainularity being
	 * used
	 * 
	 * @param name
	 *            - the name of the gatherer on which you want to query
	 * @return returns the result of a query on the gatherer's name, grainType,
	 *         and consolidation date range
	 */
	public List<List<Map<String, Object>>> gathererFilter(String name);

	/**
	 * Sets the date range on which the consolidation will take place based on
	 * the time it was called
	 */
	public void setDates();

	/**
	 * Manually sets the date range
	 */
	public void setDates(Date upperDate, Date lowerDate);

	/**
	 * Manually sets the types used for querying and defining grainType
	 * 
	 * @param grainType
	 *            -int corresponding to this grain's type
	 * @param filterType
	 *            -Integer corresponding to the grainularity of objects to
	 *            consolidate
	 */
	public void setTypes(int grainType, Integer filterType);

	/**
	 * Sets the types used for querying and setting grainType
	 */
	public void setTypes();
}
