package com.linuxbox.enkive.statistics.consolidation;

import java.util.Date;
import java.util.List;
import java.util.Map;


public interface Consolidator {
	/**
	 * Consolidates data for all the stats gatherers defined in the client
	 */
	public List<Map<String, Object>> consolidateData();
	
	/**
	 * Stores data generated by consolidateData()
	 */
	public void storeConsolidatedData();

	/** This method takes a gathername and querys the mongo database on a grainType and
	 * date range as specified by the type of grainularity being used
	 * @param name - the name of the gatherer on which you want to query
	 * @return returns the result of a query on the gatherer's name, grainType, and
	 * consolidation date range
	 */
	public List<List<Map<String, Object>>> gathererFilter(String name);
	
	/**
	 * Sets the date range on which the consolidation will take place based on the time it
	 * was called
	 */
	public void setDates();
	
	/**
	 * Manually sets the date range
	 */
	public void setDates(Date upperDate, Date lowerDate);
	
	/**
	 * Manually sets the types used for querying and defining grainType
	 * @param grainType -int corresponding to this grain's type
	 * @param filterType -Integer corresponding to the grainularity of objects to consolidate
	 */
	public void setTypes(int grainType, Integer filterType);
	
	/**
	 * Sets the types used for querying and setting grainType
	 */
	public void setTypes();
}
