package com.linuxbox.enkive.statistics.granularity;

import java.util.Date;
import java.util.Map;
import java.util.Set;


public interface Grain {
	/**
	 * consolidates data for all the stats gatherers defined in the gathererService/client
	 */
	public Set<Map<String, Object>> consolidateData();
	
	/**
	 * stores data generated by consolidateData()
	 */
	public void storeConsolidatedData();

	/** this method takes a gathername and querys the mongo database on a grainType and
	 * date range as specified by the type of grainularity you are using
	 * @param name - the name of the gatherer on which you want to query
	 * @return returns the result of a query on the gatherer's name, grainType, and
	 * consolidation date range
	 */
	public Set<Map<String, Object>> gathererFilter(String name);
	
	/**
	 * sets the date range on which the consolidation will take place based on the time it
	 * was called
	 */
	public void setDates();
	
	/**
	 * allows you to manually set the date range, or calculate it differently
	 */
	public void setDates(Date upperDate, Date lowerDate);
	
	/**
	 * sets the types used for querying and setting grainType
	 * @param grainType -int corresponding to this grain's type
	 * @param filterType -Integer corresponding to the grainularity of objects to consolidate
	 */
	public void setTypes(int grainType, Integer filterType);
}
