package com.linuxbox.enkive.docstore.exception;

/**
 * This superclass allows us to treat all exceptions generated by the
 * DocStoreService similarly.
 * 
 * @author ivancich
 * 
 */
public class DocStoreException extends Exception {
	private static final long serialVersionUID = -8935195197908675515L;

	public DocStoreException() {
		super();
	}

	public DocStoreException(String message) {
		super(message);
	}

	public DocStoreException(String message, Throwable t) {
		super(message, t);
	}

	public DocStoreException(Throwable t) {
		super(t);
	}
}
