#!/bin/bash
#
# enkive     Startup script for enkive
#
# chkconfig: - 64 36
# description: Enkive e-mail Archiver
#
# processname: enkive
#


# SYSTEM ADMINISTRATOR LIKELY WANTS TO MODIFY THE FOLLOWING VARIABLES

# user id under which Enkive is run; a good practice is to create a user specifically to run Enkive (e.g., "enkive")
ENKIVE_OWNER=enkive

# path to top-level Enkive directory; this directory would contain "lib" and "config"
ENKIVE_HOME=$(pwd)

# path to the jsvc executable file
JSVC=/usr/local/bin/jsvc

# path to top level of the Java JDK (must be a JDK and not a JRE); should contain "bin", "lib", and "lib/tools.jar"
JAVA_HOME=/usr/lib/jvm/java-openjdk

# path to directory that contains file "libindri_jni.so"
INDRI_SO_PATH=/usr/local/lib


# TESTING OF THE ABOVE

errors=0

if [ ! -f ${JAVA_HOME}/bin/javac -o ! -f ${JAVA_HOME}/lib/tools.jar ] ;then
	echo JAVA_HOME is likely set incorrectly.
	errors=1
fi

if [ ! -d ${ENKIVE_HOME}/config -o ! -d ${ENKIVE_HOME}/lib ] ;then
	echo ENKIVE_HOME is likely set incorrectly.
	errors=1
fi

if [ ! -f ${INDRI_SO_PATH}/libindri_jni.so ] ;then
	echo INDRI_SO_PATH is likely set incorrectly.
	errors=1
fi

if [ ! -f ${JSVC} ] ;then
	echo JSVC is likely set incorrectly.
	errors=1
fi

if grep --silent "^${ENKIVE_USER}:" /etc/passwd ;then
	:
else
	echo ENKIVE_USER is likely set incorrectly.
	errors=1
fi

if [ ${errors} -eq 1 ] ;then
	echo "Exiting due to error(s). See comments in $0 for guidance."
	exit 1
fi


# system administrator may not (or may) want to edit the following

ENKIVE_LOG_PATH=${ENKIVE_HOME}/data/logs
ENKIVE_PID_FILE=${ENKIVE_HOME}/data/enkive.pid
ENKIVE_CLASSPATH=${ENKIVE_HOME}/enkive.jar:${ENKIVE_HOME}/lib/*:${ENKIVE_HOME}/lib/spring/*:${ENKIVE_HOME}/config:${JAVA_HOME}/lib/tools.jar


# the following should likely not be edited

RETVAL=0

start() {
	    cd $ENKIVE_HOME
        echo -n "Starting Enkive:  "
        su $ENKIVE_OWNER -c "$JSVC -java-home $JAVA_HOME -pidfile $ENKIVE_PID_FILE -outfile $ENKIVE_LOG_PATH/enkive.log -errfile $ENKIVE_LOG_PATH/enkive.err -cp $ENKIVE_CLASSPATH -Dlog4j.configuration=file://$ENKIVE_HOME/config/log4j.properties -Djava.library.path=$INDRI_SO_PATH com.linuxbox.enkive.EnkiveDaemon"
        RETVAL=$?
        sleep 2
        echo
}

stop() {
		cd $ENKIVE_HOME
        echo -n "Stopping Enkive: "
        su $ENKIVE_OWNER -c "$JSVC -stop -java-home $JAVA_HOME -pidfile $ENKIVE_PID_FILE -outfile $ENKIVE_LOG_PATH/enkive.log -errfile $ENKIVE_LOG_PATH/enkive.err -cp $ENKIVE_CLASSPATH -Dlog4j.configuration=file://$ENKIVE_HOME/config/log4j.properties -Djava.library.path=$INDRI_SO_PATH com.linuxbox.enkive.EnkiveDaemon"
        RETVAL=$?
        echo
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        RETVAL=1
esac

exit $RETVAL
