#!/bin/bash
#
# enkive     Startup script for enkive
#
# chkconfig: - 64 36
# description: Enkive e-mail Archiver
#
# processname: enkive
#


# system administrator likely wants to edit the following variables

ENKIVE_OWNER=$(whoami)
ENKIVE_HOME=$(pwd)
JSVC=/usr/local/bin/jsvc
JAVA_HOME=/usr/lib/jvm/java-openjdk
INDRI_SO_PATH=/usr/local/lib


# system administrator may not (or may) want to edit the following

ENKIVE_LOG_PATH=$ENKIVE_HOME/data/logs
ENKIVE_PID_FILE=$ENKIVE_HOME/data/enkive.pid
ENKIVE_CLASSPATH=$ENKIVE_HOME/enkive.jar:$ENKIVE_HOME/lib/*:$ENKIVE_HOME/lib/spring/*:$ENKIVE_HOME/config


# the following should likely not be edited

RETVAL=0

start() {
	    cd $ENKIVE_HOME
        echo -n "Starting Enkive:  "
        su $ENKIVE_OWNER -c "$JSVC -java-home $JAVA_HOME -pidfile $ENKIVE_PID_FILE -outfile $ENKIVE_LOG_PATH/enkive.log -errfile $ENKIVE_LOG_PATH/enkive.err -cp $ENKIVE_CLASSPATH -Dlog4j.configuration=file://$ENKIVE_HOME/config/log4j.properties -Djava.library.path=$INDRI_SO_PATH com.linuxbox.enkive.EnkiveDaemon"
        RETVAL=$?
        sleep 2
        echo
}

stop() {
		cd $ENKIVE_HOME
        echo -n "Stopping Enkive: "
        su $ENKIVE_OWNER -c "$JSVC -stop -java-home $JAVA_HOME -pidfile $ENKIVE_PID_FILE -outfile $ENKIVE_LOG_PATH/enkive.log -errfile $ENKIVE_LOG_PATH/enkive.err -cp $ENKIVE_CLASSPATH -Dlog4j.configuration=file://$ENKIVE_HOME/config/log4j.properties -Djava.library.path=$INDRI_SO_PATH com.linuxbox.enkive.EnkiveDaemon"
        RETVAL=$?
        echo
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        RETVAL=1
esac

exit $RETVAL
